wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.6
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      4: 3.8.6
      5: 0.10.33
      8:
      - 1
      - 3
      - 5
    viz:
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
architecture:
  desc: null
  value: Linear
dataset:
  desc: null
  value: wine dataset
epochs:
  desc: null
  value: 100
fc_layer_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: NLLLoss
optimizer:
  desc: null
  value: sgd
