wandb_version: 1

architecture:
  value: Linear
dataset:
  value: wine dataset
hidden_size:
  value: 117
input_size:
  value: 26
learning_rate:
  value: 0.0061976150012072115
loss:
  value: NLLLoss()
output_size:
  value: 3
