wandb_version: 1

architecture:
  value: Linear
dataset:
  value: wine dataset
hidden_size:
  value: 186
input_size:
  value: 20
learning_rate:
  value: 0.018638395920396605
loss:
  value: NLLLoss()
output_size:
  value: 6
